### ISSUE TITLE
Scrobbling 

### ISSUE THREAD

**Issue by Canelparne** [TT-ReBORN/Georgia-ReBORN#101]
Hey. Is scrobbling not supported in this ? I've also tried using a scrobbling component I downloaded but it didn't work. After I set up my username and everything in the window and I exit, it just resets everything back

**Comment by TT-ReBORN** [comment]
Tested with foobar2000_v1.6.16 and Georgia-ReBORN Beta 11 and last.fm scrobbling works.

Download [foo_scrobble](https://github.com/gix/foo_scrobble/releases) and install the component.
Then go in foobar's preferences > Tools > Last.fm scrobbling.
Just click on the Request authorization button and your browser will ask for your username and password.
Log in and allow the request, head back to foobar and now the `Request authorization button` will be displayed as 
`Complete authorization`. Click on it to finish the process and restart foobar. 
To be sure that everything is correctly setup, go again to foobar's preferences > Tools > Last.fm scrobbling
and the button now displays as "Clear authorization". You can now listen to songs and it will be scrobbled.

If you have a new account, you will need to listen to 2 or 3 songs and your scrobbling will be registered
to your last.fm account.

-TT

**Comment by TT-ReBORN** [comment]
Yes, radio streaming will be also scrobbled.

-TT
