### ISSUE TITLE
Doesn't seem to work with Foobar2000 v2.0 

### ISSUE THREAD

**Issue by alirezameftahi71** [TT-ReBORN/Georgia-ReBORN#115]
I installed the latest version of Foobar200 v2.0 (stable release 64 bit) on Widows 10

It's not portable installation, so I extracted the content of the profile directory into `%AppData%\foobar2000-v2`
I opened the program but I wasn't prompted by any message. 
This theme is not compatible with v2.0 it seems. Am I right?
And if it is not compatible, Do you have any plans to make it compatible with v2.0?

**Comment by TT-ReBORN** [comment]
The answer to your question was already answered here: https://github.com/TT-ReBORN/Georgia-ReBORN/issues/102
