### ISSUE TITLE
Guide to install never mentions the need to install x86 foobar2000

### ISSUE THREAD

**Issue by autumn876** [TT-ReBORN/Georgia-ReBORN#116]
title, it would be nice, I spent quite a while trying to troubleshoot, I only found it out by looking at a months old git issue that is nowhere near easily accessible, not even in the faq.

**Comment by TT-ReBORN** [comment]
Sorry for the inconvenience, foobar2000 v2.0 is new and I've forgot to update the readme.
I've put the notice in the installation instructions, thanks for the report.

-TT
