### ISSUE TITLE
It keeps using the wrong album art

### ISSUE THREAD

**Issue by wentallout** [TT-ReBORN/Georgia-ReBORN#117]
![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/76118931/fec08ce1-13dd-43a2-8219-133dc0dc9b54)

All my music files are all properly tagged and have its own album art. For some reason the player keep using one random image on my computer.

**Comment by TT-ReBORN** [comment]
Hi @wentallout, 

you need to have one of those as your album cover in your music album folder:
folder.jpg/png
cover.jpg/png
front.jpg/png

[If you want to use embedded album art covers and are using the Beta version from here](https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/74#discussion-4190799):
Go to top menu Options > Player controls > Album art > Load embedded album art first
Now go to top menu File > Preferences. Advanced ( Bottom ) > Go to section Album art > Embedded vs external > Prefer embedded. Restart foobar.

-TT
