### ISSUE TITLE
Instantly crashes upon launch

### ISSUE THREAD

**Issue by Katamaranthine** [TT-ReBORN/Georgia-ReBORN#120]
Hello. 
This error happened yesterday out of the blue. It happened on first boot of the day and I've been running Georgia-Reborn for over a year now, maybe. No changes in settings whatsoever, didn't update foobar2k.
https://ibb.co/V9Xsrhx

I can still play music but I never get the UI anymore. I get the same error but music somehow plays in the background (when I manually select the file in file explorer).

I am running Windows 10.
https://ibb.co/n38wzGs

**Comment by TT-ReBORN** [comment]
You're using a very old version, please update to the latest.
https://github.com/TT-ReBORN/Georgia-ReBORN/releases

-TT

**Comment by Katamaranthine** [comment]
Updated the theme, working again. Thanks!
