### ISSUE TITLE
Track elapsed/remaining time not displaying properly

### ISSUE THREAD

**Issue by AdumbP** [TT-ReBORN/Georgia-ReBORN#122]
Not sure if this was addressed anywhere else but I cant get the track time to display properly. It's drawing in with the track info above the seek bar super weirdly. Using foobar 2.0 32 bit, tried to change display and layout but it persists. I'm a huge pleb for this kinda stuff so it may be user error. Might not even be a bug (sorry)! Any help would be appreciated!

![foobar2000_06_12_19_05 (2)](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/109823068/ab1804f1-64c5-431a-b1c8-80f277f369a6)
![foobar2000_06_12_19_05](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/109823068/22dc4538-e17b-4e61-af18-b23788589bcd)

**Comment by TT-ReBORN** [comment]
Hi,

I have never saw this issue, what Georgia-ReBORN version are you using? 
The latest from here https://github.com/TT-ReBORN/Georgia-ReBORN/releases ?
It's possible you're using the very old version before I have updated Github, if so please update it.

If not, tell me: 
- What is your monitor resolution?
- What display mode you're using? ( top menu Options > Display )
- Did you change the font sizes? ( top menu Options > Font size )

-TT

**Comment by AdumbP** [comment]
Hey TT thanks for replying. I decided to nuke foobar and fully uninstalled, restarted and reinstalled with a portable install this time. Everythings fixed now. Thanks for your awesome work! Looks fantastic now.
