### ISSUE TITLE
Rose Pine Custom Theme

### ISSUE THREAD

**Issue by Mojas84** [TT-ReBORN/Georgia-ReBORN#126]
Hi please would it be possible to create Rose Pine Custom theme?? Dark desert is good but have rose pine theme for win11....

**Comment by TT-ReBORN** [comment]
Hi @Mojas84,

you can create as many custom themes as you wish, it's really up to the user. The existing georgia-reborn-custom.jsonc file
located in your `foobar2000\profile\georgia-reborn\configs\` directory, contains the 10 official Georgia-ReBORN custom themes. Rename this config file or move it to another directory and reload the theme, this will create a new default
georgia-reborn-custom.jsonc file in the folder. You will now have the default template with 10 slots.

Now go to top menu `Options > Theme > Custom > Edit custom theme`.
The custom theme menu will open, select from the menu `Options > Info` and read the description first.
From the custom theme menu, go to `Options > Theme 02`. This will automatically select custom theme slot 02.
Now change the colors as you like via pasting the HEX color code or use the color picker, 
the colors will be automatically written and updated to your new georgia-reborn-custom.jsonc file. 
It is helpful for new users to click on the :bulb: icon next to the input HEX color code, 
this will mark and show you what color is assigned to which UI element.

If you have finished your custom theme/s, you can showcase it in this thread here: https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/99

**Good to know:** If you're using the Reborn theme and you have discovered great colors from an album, 
you can automatically save them when you use `Options > Theme > Custom > Save current colors` and select a slot.
You can now select the theme via `Options > Theme > Custom` and select the slot you have previously saved it.
When the custom theme is active, you can rename the slot via `Options > Theme > Custom > Rename custom theme`

-TT
