### ISSUE TITLE
Theme keeps crashing. Not sure what to do anymore

### ISSUE THREAD

**Issue by Woof420** [TT-ReBORN/Georgia-ReBORN#127]
Hi.

I had been using an old version of georgia reborn (at least 1 year old release) and it was working fine until something changed and I started getting random crashes. They mostly happen after foobar2k is open and I double click on a track in a different folder (i don't like navigating my library within the program, I go folder to folder).

I updated to the latest version and it was fine for a while...until I recently started getting a new (or perhaps the same) issue. I don't know what is going on. I've uninstalled an reinstalled foobar2k and it seems to go away until I reboot and then the issue happens non-stop. The only thing I change after a reinstall is adding keyboard shortcuts for skip ahead 5, 10 and 30 secs and another for back in the same intervals. And changing the default media location.

This is the error I'm getting:

Error: Spider Monkey Panel v1.6.1-mod ({04620F16-1878-47A1-8EFE-0CE0B99566CC}: Georgia-ReBORN v3.0-RC1 by TT)
Find failed:
handle argument is null

File: main.js
Line: 2537, Column: 26
Stack trace:
  set_now_playing_hyperlink/<@main.js:2537:26

![bug](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/135785312/feab8ec9-0466-4839-b7ea-8734359ae8ad)

What does it mean?

**Comment by TT-ReBORN** [comment]
Hi @Woof420,

I have already fixed this issue some days ago and will be available in V3.0RC2, but you can already download it 
from the [master here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip). Just replace your files and all should be good.

-TT

**Comment by Woof420** [comment]
Awesome! Thanks a lot for the quick reply and the fix. I like this theme a lot and I was worried about having to test old versions until I found one that worked or an alternative theme. I just tested the new version and I think it's completely fixed.
