### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by thewayur** [TT-ReBORN/Georgia-ReBORN#129]
i deleted the profile from portable.
now red screen with error.

what is uninstallation process?

**Comment by TT-ReBORN** [comment]
Hi @thewayur,

yes, deleting ONLY the profile is enough. 
On next foobar startup it will recreate the default profile and there should be no error, everything should be default.

What error do you have? Please post it here.

-TT

**Comment by TT-ReBORN** [comment]
It seems this is a problem on the user side, I'm closing this now as there is no further information provided.
