### ISSUE TITLE
Scrollbar visibility is reset when using filters in Library view

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#13]
In the playlist view, right click > Appearance > Show scrollbar. Open Library view and use the dropdown filter to select any option. Return to playlist view by deselecting the Library button at the top, and the playlist scrollbar visibility has been reset and is now hidden.

**Comment by TT-ReBORN** [comment]
Thanks for the bug report, the issue has been fixed!

**Comment by takaji10** [comment]
I'm not sure if the issue is fully fixed - I noticed that if I move the mouse over the playlist panel and then off of the foobar2000 window that it will randomly disappear and reappear.

Tried to capture it in a gif: https://i.gyazo.com/0e421bcd1e7341930a73e5abdaa560d7.gif
