### ISSUE TITLE
How to modify playlist width in the default layout

### ISSUE THREAD

**Issue by Cerallin** [TT-ReBORN/Georgia-ReBORN#134]
I always make foobar2000 fullscreen on a 3840x1100 screen. There appears to be a minor issue: the cover art is floating right with the Georgia-ReBORN theme.

<img width="1920" alt="image" src="https://github.com/TT-ReBORN/Georgia-ReBORN/assets/66366855/29fd5249-52eb-44b6-b3f5-ae78f41b8115">

I wonder if there is a way to change the width ratio of the cover art and the playlist. Or centering the cover art is also okay with me.

Thank you very much.

**Comment by TT-ReBORN** [comment]
Hi @Cerallin,

you can only make the playlist full width when you right click somewhere in the playlist panel 
for context menu > Change layout to full. To go back: right click again > Change layout to normal.

For the album art, you have the following options:
In top menu Options > Player controls > Album art > When player size is not proportional.
In top menu Options > Player controls > Album art > When player size is maximized/fullscreen.

-TT

**Comment by Cerallin** [comment]
Thank you for your reply. And I'd like to know if the playlist width is configured by the JavaScript files. If so, I may help add this feature. However, I've never developed foobar200 themes before. It would be nice if you could tell me how to do the modification.

**Comment by TT-ReBORN** [comment]
Yes, it's controlled via JavaScript. Actually I'm finishing full code documentation for fellow developers to navigate and understand the code and infrastructure better. Thanks for the offer but I'll this myself, it would be faster than to explain all the stuff.

**Comment by TT-ReBORN** [comment]
@Cerallin,

I have implemented the panel auto width feature which will adjust its panel size based on the player size width.
Everythings works fine but I can not test it in fullscreen/maximized because I do not own such monitor ( QHD/WQHD or other super wide panorama res monitor ). Can you test it for me when I send you the files?

-TT

**Comment by Cerallin** [comment]
@TT-ReBORN Sure I'm glad to do the tests.

**Comment by TT-ReBORN** [comment]
Here you go: https://filepost.io/d/TwbtUg6dML

What you need to test is simple:
First activate the new auto panel width via top menu: 
Options > Player controls > Panel > Width > Use auto panel width.

Then you need to change the default album art position via top menu: 
Options > Options > Player controls > Album art > When player size is not proportional > Align album art left.

Now with your mouse cursor go to the edge of the player and manually enlarge the player size width and see how the
Playlist, Library, Biography and Lyrics panels will auto adjust the width size.
Also test this with the other two album art align options: 
Options > Player controls > Album art > When player size is not proportional > Align album art left (margin).
Options > Player controls > Album art > When player size is not proportional > Align album art center.

**This should all work for you as I could test this myself. But now you should test and try with maximized/fullscreen.**
Maximized player state is: 
When you double click on top menu bar, this will maximize, when you double click again it will resume your last player size.
Fullscreen you already know ( fullscreen button at the top right corner ).

Basically you only need to test and try all the align album art options in maximized and fullscreen mode
and see if the panel auto width does work properly in these modes.

---

**If it does not work, you need to fix it please.**
`pref.panelAutoWidth` is the setting we use. I guess you would need to adjust the position in gr-main-functions.js:

in line ~ 1978, function resizeArtwork(resetDiscArtPosition) {

```
		albumArtSize.x = // * When player size is not proportional, album art is aligned via setting 'pref.albumArtAlign' in Default layout and is centered in Artwork layout */
			pref.layout === 'default' ?
				displayPlaylist || displayLibrary ?
					UIHacks.FullScreen || UIHacks.MainWindowState === WindowState.Maximized ? ww * 0.5 - albumArtSize.w :
					pref.albumArtAlign === 'left' ? 0 :
					pref.albumArtAlign === 'leftMargin' ? ww / wh > 1.8 ? SCALE(40) : 0 :
					pref.albumArtAlign === 'center' ? Math.floor(xCenter - 0.5 * albumArtSize.w) :
					ww * 0.5 - albumArtSize.w :
				Math.floor(xCenter - 0.5 * albumArtSize.w) :
			pref.layout === 'artwork' ? !displayPlaylist || pref.displayLyrics ? ww * 0.5 - albumArtSize.w * 0.5 : ww : 0;
```

Tell me how it goes, thanks for the help =)

-Tom

**Comment by TT-ReBORN** [comment]
What I have quickly noticed, I forgot to add this extra condition in the above code posted:
replace:
`pref.albumArtAlign === 'leftMargin' ? ww / wh > 1.8 ? SCALE(40) : 0 :`
to:
`pref.albumArtAlign === 'leftMargin' ? pref.panelWidthAuto || (ww / wh > 1.8) ? SCALE(40) : 0 :`

**Comment by Cerallin** [comment]
Aligning album art left or left works fine. I'm not sure if `align center` works as you expected: It appears the same as aligning left (margin), and the only difference is the margin size. I guess there should be a margin between the cover art and the playlist.

The `pref.albumArtAlign` seems not to be working in `UIHacks.FullScreen` and `UIHacks.MainWindowState`. I replaced
```javascript
UIHacks.FullScreen || UIHacks.MainWindowState === WindowState.Maximized ? ww * 0.5 - albumArtSize.w :
```
with
```javascript
UIHacks.FullScreen || UIHacks.MainWindowState === WindowState.Maximized ? 0 :
```

to see how it looks, and the result is shown below.

<img width="1920" alt="Screenshot 2023-07-26 091206" src="https://github.com/TT-ReBORN/Georgia-ReBORN/assets/66366855/e2af8a76-3572-475f-91ab-0e7b163c5e06">

**Comment by TT-ReBORN** [comment]
Here is the fixed code, this should work:

A little bit above the code starting from `if (displayPlaylist || displayLibrary) {`  replace with this:

```
		if (displayPlaylist || displayLibrary) {
			xCenter =
				pref.layout === 'artwork' ? 0 :
				UIHacks.FullScreen && !pref.panelWidthAuto ? RES_4K ? 0.261 * ww : 0.23 * ww :
				UIHacks.MainWindowState === WindowState.Maximized && !pref.panelWidthAuto ? RES_4K ? 0.267 * ww : 0.24 * ww :
				xCenter = 0.25 * ww;
		}
		else if (ww / wh < 1.40) { // When using a roughly 4:3 display the album art crowds, so move it slightly off center
			xCenter = 0.56 * ww; // TODO: check if this is still needed?
		}
		else {
			xCenter = 0.5 * ww;
			artOffCenter = false;
			if (albumScale === 0.75 * ww / albumArt.Width) {
				xCenter += 0.1 * ww;
				artOffCenter = true; // TODO: We should probably suppress labels in this case
			}
		}

		const noAlbumArtSize = wh - geo.topMenuHeight - geo.lowerBarHeight;
		albumArtSize.w = Math.floor(albumArt.Width * albumScale); // Width
		albumArtSize.h = Math.floor(albumArt.Height * albumScale); // Height
		albumArtSize.x = // * When player size is not proportional, album art is aligned via setting 'pref.albumArtAlign' in Default layout and is centered in Artwork layout */
			pref.layout === 'default' ?
				displayPlaylist || displayLibrary ?
					pref.albumArtAlign === 'left' ? 0 :
					pref.albumArtAlign === 'leftMargin' ? SCALE(40) :
					pref.albumArtAlign === 'center' ? Math.floor(xCenter - (0.5 * (noAlbumArtStub ? noAlbumArtSize : albumArtSize.w))) :
					Math.floor(ww * 0.5 - (noAlbumArtStub ? noAlbumArtSize : albumArtSize.w)) :
				Math.floor(xCenter - (0.5 * (noAlbumArtStub ? noAlbumArtSize : albumArtSize.w))) :
			pref.layout === 'artwork' ?
				!displayPlaylist || pref.displayLyrics ? Math.floor(ww * 0.5 - albumArtSize.w * 0.5) : ww : 0;
```

---

It should look like this:

![align_album_art_left](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/b26fb77e-0a86-46a4-b3f4-d80cf611016a)

![align_album_art_left_margin](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/49a2d2d2-337d-4bd9-92d0-99f6fd766bc4)

![align_album_art_center](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/d58607bd-f69d-43ea-841b-827394f45e8e)

![align_album_art_right](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/ab23d110-3b69-48c6-b1fa-4d4c88915fb6)

---

Keep in mind album art centered is based on the whole width. 
If everything is good, I'll commit to master.

-Tom

**Comment by Cerallin** [comment]
I've tested them, and they all worked fine. Thank you very much for your patience.

**Comment by TT-ReBORN** [comment]
Implemented in https://github.com/TT-ReBORN/Georgia-ReBORN/commit/e907d6c0b30944c3e3021e044bcf711f01ee78c6.
