### ISSUE TITLE
Playlist Padding

### ISSUE THREAD

**Issue by chr1sx** [TT-ReBORN/Georgia-ReBORN#135]
Hello. Is it possible to remove padding in the playlist? Seems like some space is wasted, especially in titles.

![Clipboard01](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/12203573/732eef72-24af-4b1b-9887-b2a1fb8f8c14)

Thanks!

**Comment by TT-ReBORN** [comment]
Hi @chr1sx,

all margins and paddings in this layout have been carefully optimized. 
There is no way to remove these because the top and bottom margin are actually rectangles with filled background color 
to hide unwanted playlist rows that shouldn't be visible when scrolling. If there wouldn't be these rectangles, 
ugly redraw leftovers would be visible. Artist/titles in the playlist rows get truncated when the width has not enough space.
This space is actually reserved for rating. If your tracks had rating, yellow stars would be displayed.

-TT

**Comment by chr1sx** [comment]
Ah, I see. Thanks for the replay and explanation! Is it possible to disable rating and whatever else, to have more space for the titles?

**Comment by TT-ReBORN** [comment]
Yes, go to top menu Options > Playlist > `Show play count` and `Show rating`. 
Deactivate both and I think you will have more space available.

**Comment by chr1sx** [comment]
Great! This is the best thing ever happened to Foobar, thank you!

**Comment by TT-ReBORN** [comment]
Glad you like it, be sure to update to RC-2 once released. Will be available soon.

**Comment by chr1sx** [comment]
To not make another thread, I stumbled on this feature.
Whenever I press ctlr+a/z/c etc hotkeys in playlist, my keystrokes would appear in the center, until I restart. Any advice how to make it go away or disable it?

![Clipboard01](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/12203573/95bd2a3d-648a-485d-9c19-5b63e4c42102)

**Comment by TT-ReBORN** [comment]
This issue has been fixed in the master some time ago, [download it](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip) and replace your files.

**Comment by chr1sx** [comment]
Hey again! Sorry to bother you, but do you know why Ctrl+z does not work anymore after installing Georgia-Reborn? I find pretty useful in playlists..

**Comment by TT-ReBORN** [comment]
Ctrl + z is the default "Undo" action? I will look into this.

**Comment by chr1sx** [comment]
Yeah, that's undo, like when you delete something from playlist, it reverts that action. It still works with Edit > Undo, but not the hotkey.

**Comment by TT-ReBORN** [comment]
This has never worked in the theme but I have implemented it. You can [download the master](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip) and replace your files. 
Btw, you can use the playlist history ( undo < > redo ) buttons at the playlist top header when you move your mouse over it.
This has the same effect and also remembers playlists when you change to others with maximum 10 history steps.
