### ISSUE TITLE
Playlist manager in playlist view displays a lock icon that falls off the window

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#14]
In playlist view, right-click > Appearance > Show playlist manager. The playlist manager displays a small lock icon that is partially cut off by the edge of the screen.

See screenshot:

![image](https://user-images.githubusercontent.com/1534470/125156243-c8656700-e164-11eb-9867-dbf28f5e4221.png)

**Comment by TT-ReBORN** [comment]
How did you manage to get the lock? Never saw/encountered this one, tried all sizes and fullscreen and can't reproduce...

**Comment by takaji10** [comment]
I'm not sure actually. I'm on a 2560x1440 resolution desktop with the player taking up a quarter of the screen.

**Comment by TT-ReBORN** [comment]
Got it figured out now, you have foo_utils installed and locked your playlist. 
If this component is installed, you have an additional menu option 'Lock Current Playlist' when you click on the playlist manager.

**Comment by TT-ReBORN** [comment]
Try it now, should be fixed!
