### ISSUE TITLE
album art does not change

### ISSUE THREAD

**Issue by WuSix42** [TT-ReBORN/Georgia-ReBORN#140]
If I go onto the library tab and play from this tab some album and then play another album of the same artist, the album art doesn't change.

What can I do to solve it, or is it unsolvable without code invasion? I can also remove this bug with code, but if so, let me know what to edit because I am not a pro in JS.

~~By the way, how do I add artist art and show album art in the library?~~
P.S. I found how to do that

**Comment by TT-ReBORN** [comment]
So is this issue in RC-1 or the current master version?

**Comment by WuSix42** [comment]
in RC-1

**Comment by TT-ReBORN** [comment]
Can you try the latest master? 
[Download from here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip) and replace your files. 
If the issues is still present, tell me step by step how to reproduce so I can fix it, thanks!

**Comment by TT-ReBORN** [comment]
So did you solve this? 

Just be sure that your album folder has either folder.jpg/png or if the album art is embedded and you want to prefer embedded album art only, go to top menu Options > Player controls > Album art > Load embedded album art first. 
Then go to foobar Preferences > Advanced > Display > Album art > Embedded vs external > Prefer embedded.
Restart foobar.

-TT

**Comment by TT-ReBORN** [comment]
No response, I am closing this now.
