### ISSUE TITLE
How to display "Hi-res" logo?

### ISSUE THREAD

**Issue by Roif-X** [TT-ReBORN/Georgia-ReBORN#142]
_Thank you for your development work, great work! Even though some of the logic is a bit cumbersome, it's a pleasure to use it after some fiddling with the configurations._

  **Back to the topic, I found the 'Hi-res' logo in the installation directory, but I don't see him in the software interface, will he show it under certain conditions? If not how to enable this feature to show hi-res logo?**

(This text is machine translated, please forgive me if it doesn't make sense)

**Comment by TT-ReBORN** [comment]
Hi @Roif-X,

glad you like the theme. You need to enable the Hi-Res Audio logo via 
top menu `Options > Player controls > Album art > Show hi-res audio badge on album cover`.

Your music files also need to be at least in 24 bit depth when playing.

-TT

**Comment by Roif-X** [comment]
Okay,  It can be displayed now. Thanks for your reply, Have a great day. 😃
