### ISSUE TITLE
Unable to load fonts after restarting the OS

### ISSUE THREAD

**Issue by zhangdoa** [TT-ReBORN/Georgia-ReBORN#158]
Hello!

I have to reinstall all the fonts each time after I'd restart my system (Windows 11 Pro 23H2, 22631.2792) because otherwise, there would be “font not found” errors in the log. I've identified it's the TestFont function in profile\georgia-reborn\scripts\Base\gr-helpers.js that it won't return true when Foobar2000 is launched without reinstalling the fonts, and since it relies on foo_spider_monkey_panel and then Windows GDI+ API, I wonder if you could either fix it on your side or report it to the maintainers?

(Also, thanks for making this theme, it's awesome!)

**Comment by TT-ReBORN** [comment]
Hi @zhangdoa,

you are at the right place, I am the dev and maintainer of Georgia-ReBORN.

There shouldn't be any issues regarding fonts if installed correctly. You are the first to report this issue.
How did you install the fonts? Via right click `Install as administrator` or `Install for all users`? 
Or did you manually copy all fonts into `C:\Windows\Fonts`?
Are all fonts available in `C:\Windows\Fonts` when you restart your Windows?

The `TestFont` is not the issue, it is just a callback to Spider Monkey Panel's `utils.CheckFont` that checks 
if the OS has the font installed.

-TT

**Comment by zhangdoa** [comment]
Hi @TT-ReBORN,

Thanks for the reply! I tried again with "Install for all users" and seems the missing error won't appear anymore. The option is hidden by default from the right-click options on Windows 11, I'd suspect the default "Install" there wasn't doing something correct. Also, `C:\Windows\Fonts` has the installed fonts since the first ever time I installed the theme, so it was also confusing why the check won't pass.

Best,
zhangdoa

**Comment by TT-ReBORN** [comment]
It is possible that you were using old fonts installed on your Windows. 
I remember that I have changed the metadata font names and file names since version RC-1.
This could lead that the fonts were not detected correctly...

Anyways, glad you solved it!

-TT
