### ISSUE TITLE
Separate playlists for library view and currently playing queue

### ISSUE THREAD

**Issue by pmi** [TT-ReBORN/Georgia-ReBORN#165]
First of all, thanks for all the great work ! 🎉 

One thing I miss though is ability to set up different playlists for library view and currently playing queue.

I have set up library view in split mode so that:
- Single click sends album to playlist in order to be able to see the song list
- And the double click sends the album to playlist and plays it

And my main problem is that both of these actions use the same playlist so browsing library after sending something to playback will overwrite the playback queue. 

Would be nice to be able to see album contents without changing the playback queue in the following fashion:
- When I activate library tab, library playlist would show up
- Single click would send albums there to show the contents
- Double click though would send albums to the playback queue playlist
- Turning library tab off would then switch to now playing queue playlist

I wonder if this can this be configured or more are substantial changes needed ?
Thanks !

**Comment by TT-ReBORN** [comment]
Hi @pmi,

did you check the FAQ: [Why does it play only one song and does not continue the album?](https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/58#:~:text=Why%20does%20it%20play%20only%20one%20song%20and%20does%20not%20continue%20the%20album%3F)

It seems you are always working in the `Library View` auto-playlist. The content for this auto-playlist will be always overwritten with the Library single/double click actions. Think of the `Library View` playlist as a temp playlist when you playing stuff from the Library. Just make new playlists and add your albums there. You can then easily switch between the playlists, more information in this FAQ: [How do I create playlists and access the playlist manager?](https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/58#:~:text=How%20do%20I%20create%20playlists%20and%20access%20the%20playlist%20manager%3F)

Library single/double click actions can be configured via top menu `Options` > `Library` > `Controls`.
And you can activate top menu `Options` > `Player controls` > `Scrollbar` > `Playlist` > `Auto-scroll to current playing song`.

Hope this information helps.

-TT

**Comment by pmi** [comment]
Thanks !

It answers part of my question, the remaining one is how to access now playing playlist then ?

I couldn't find one in the playlist manager and the default one is always empty.

**Comment by TT-ReBORN** [comment]
When you hover over the playlist manager text link button ( move your mouse at the very top of the playlist bar )
left click on the playlist manager text link button ( this is a shortcut for top menu > Playlists ), it will open a popup menu 
where all your playlists are listed. The current playing playlist has the `(now playing)` string indicator next to the playlist name. When you right click on the playlist manager text link button, it will open the playlist manager popup list.

When you are in the Playlist, you can right click for Playlist context menu > Show now playing.
This will automatically switch to the playing playlist from where the song has started playing.
Top menu `Options` > `Player controls` > `Scrollbar` > `Playlist` > `Auto-scroll to current playing song`
is actually an `auto-show now playing` feature. It will always switch to the playing playlist
when changing from a different panel ( e.g Details, Biography, Library ) back to the Playlist.

It is also a pretty cool feature when playback order is `Shuffle` and then use the `Next` transport button:
![Playback_Order_Shuffle](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/222c5584-6d44-40d7-a233-e38e205bf5b1)
It will automatically scroll to the playing track.

-TT

**Comment by TT-ReBORN** [comment]
@pmi, I am closing this now.

I have implemented a new "AddTracks" button in the latest commit: https://github.com/TT-ReBORN/Georgia-ReBORN/commit/3c60e2e2d5aa953856a267f8ae350d9599d77572

Read the information in the commit message. 
You can display the new "AddTracks" button and configure the playlist where you want to add your albums/tracks.

-TT
