### ISSUE TITLE
Crash On change Library View

### ISSUE THREAD

**Issue by PSVLTT** [TT-ReBORN/Georgia-ReBORN#172]
Hi TT,
When I change the Library View to ULtra Modern 
it is crashed
I want to ask how to change it back to normal WITHOUT reset config or re-install theme.
I want to keep my config

Then, next I want to edit display rows infor and orders of metadata in DETAILS tab, what file I can edit?

Thank you!

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/142076226/3cf5807f-4059-411d-b0a7-113d23f154bf)

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/142076226/413c08b3-ea5d-4e8b-8500-423ebd93e8fb)

**Comment by TT-ReBORN** [comment]
Hi @PSVLTT,

I don't know which version you are using but there are no issues in version RC-2 and the master DEV version
when changing the Library's design to Ultra-modern and then back to Georgia-ReBORN.

---

Did you make a theme backup?

> To make a theme backup, go to top menu `Options > Settings > Theme backup > Make backup`.
> To restore a theme backup, go to top menu `Options > Settings > Theme backup > Restore backup`.

Also updating Georgia-ReBORN is pretty easy, even with old user configs:

> 01. Please make a theme backup via `Options > Settings > Theme backup > Make backup`.
> 02. Now make a new portable foobar install and install the latest DEV master version from here:
> https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip
> 03. After you have downloaded and installed the theme, copy from your old foobar your theme backup folder:
> `foobar2000_old\profile\backup`
> to your new:
> `foobar2000\profile\backup`
> 04. Then copy the new custom config from: 
> `foobar2000\profile\georgia-reborn\configs\georgia-reborn-custom.jsonc`
> to your backup directory:
> `foobar2000\profile\backup\profile\georgia-reborn\configs\`
> 05. Now restore your theme backup via `Options > Settings > Theme backup > Restore backup`

---

I don't know if you are **stuck** with the red screen and can not start Georgia-ReBORN:
You can right click on the red screen > Panel properties... and then click on the `Clear` button and `OK`.
This will load all Georgia-ReBORN's default theme settings, you can then load your saved settings from your
config via top menu `Options` > `Settings` > `Theme configuration` > `Load settings from config file`.

---

Before you edit the metadata grid, make a backup of your config file if something goes wrong: 
`foobar2000\profile\georgia-reborn\configs\georgia-reborn-config.jsonc`

For only editing the title format patterns, `you can right click on the metadata grid` > `Edit metadata grid`.
For re-arranging the orders and also editing the title format patterns, I would recommend to make changes directly in your
`foobar2000\profile\georgia-reborn\configs\georgia-reborn-config.jsonc`

Open your config and go to the section `"metadataGrid"`.
You should not change the **original label names**, but you can change the order and the pattern, i.e value.
You can also add new metadata entries with new names and patterns, see placeholders -> Blank 01- 08.
When editing, be careful not miss any apostrophes, brackets and commas.

Also keep in mind to fully display all metadata in Details, you need to have enough metadata grid height, 
i.e a large player size.

-TT

**Comment by PSVLTT** [comment]
Thank you for advanced detailed answer.
I will try it now.

**Comment by PSVLTT** [comment]
Hello @TT-ReBORN ,
Sorry for long respond cause my PC problems.
Everything is working fine now.
Thank you very much!
