### ISSUE TITLE
Unable to set Default user interface to "Dark"

### ISSUE THREAD

**Issue by kyxap** [TT-ReBORN/Georgia-ReBORN#176]
Hi there,

I'm wandering if this possible to use "dark" default user interface with this theme? At this time it seems like this option is ignored and if I'm using dark theme the default ui is always "light" which is not really optimal. Users still uses the default ui in context menus for different reasons:
- file renaming\convert\etc
- going through the menu on top
- any right mouse click gives you pop
- etc

<img width="851" alt="image" src="https://github.com/TT-ReBORN/Georgia-ReBORN/assets/3080529/1ee6b9ae-17b1-404a-bd21-c4da7d2cc79b">

**Comment by TT-ReBORN** [comment]
Hi @kyxap,

Georgia-ReBORN is not using DUI ( Default User Interface ) but it is using CUI ( Columns UI ).
In your screenshot, go to `Columns UI` > `Coulors and fonts` > `Dark`.

-TT

**Comment by madindehead** [comment]
I have dark mode set via the `Columns UI` > `Colours and fonts` > `Dark`, but when using Windows 11 and 32-bit foobar2000 (as required) I see the following message: 

`Your version of Windows has not been tested for dark mode compatability. Some dark mode features have been disabled. `

This appears to only show in 32-bit foobar - not 64-bit foobar. Are there any known workarounds for this? Seems strange to only show in 32-bit foobar.
