### ISSUE TITLE
Can not restore the Backup

### ISSUE THREAD

**Issue by PSVLTT** [TT-ReBORN/Georgia-ReBORN#180]
Hi TT,
How are you,
I got some problem
I can not restore the backup
It is show
![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/142076226/b6639475-cea3-42a7-b26d-c76849f6f66a)
But I have backup recently
![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/142076226/a7edd596-375c-4de1-b36b-aa1ee15fa24b)

How to fix this, thank you!

**Comment by TT-ReBORN** [comment]
Hi @PSVLTT,

it seems you have a very old theme backup because you do not have the `configuration` directory in your screenshot.
In newer Georgia-ReBORN versions, the `configuration` dir will be also saved with its foobar and user-component 
config files.

---

First of all, keep a copy of your old `backup` dir with all its files.
Try to make a new theme backup with your new installed foobar, it should now have a newly created `configuration` dir 
in the backup dir. Now copy and replace all of your old `backup` dir with the newly created `backup` dir.
Restore the new theme backup.

-TT

**Comment by silverwings15** [comment]
is it possible to carry over the playback statistics from v1 to v2?

**Comment by PSVLTT** [comment]
> Hi @PSVLTT,
> 
> it seems you have a very old theme backup because you do not have the `configuration` directory in your screenshot. In newer Georgia-ReBORN versions, the `configuration` dir will be also saved with its foobar and user-component config files.
> 
> First of all, keep a copy of your old `backup` dir with all its files. Try to make a new theme backup with your new installed foobar, it should now have a newly created `configuration` dir in the backup dir. Now copy and replace all of your old `backup` dir with the newly created `backup` dir. Restore the new theme backup.
> 
> -TT
I created the backup point just 10 mins before restoration.
I used normal way to restore it now, and it is work. I will try your solution.

Thank you.

**Comment by TT-ReBORN** [comment]
@PSVLTT,

> I created the backup point just 10 mins before restoration.

This does not matter when you are using the old Georgia-ReBORN theme backup version where saving the `configuration` dir
was not implemented. The newer Georgia-ReBORN versions should save your current `configuration` dir.

---

I have tried theme backup for standard installation and it works just fine.

## Folder structure for standard foobar installation:

## Root:
![standard_installation_backup1](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/1b26c374-cfa9-4a49-b969-a74d5baf2fd7)

## Backup:
![standard_installation_backup2](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/c07d9d9c-5416-4ffe-a41b-e22b293c81ae)

---

## Folder structure for portable foobar installation:

## Root:
![portable_installation_backup1](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/b1aa4b59-c442-47b9-af3f-f21bce0fe490)

## Backup:
![portable_installation_backup2](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/dd8ce67e-d4d1-4867-96e0-dfb342744ddd)

---

Look at each path marked in the rectangle, I hope this helps and clarifies, 

-TT

**Comment by silverwings15** [comment]
@TT-ReBORN so i think when i updated my old 1.6 foobar setup to 2.x, it wiped out my track ratings and playback statistics. in addition to foobar-v2 appdata folder, there's still a regular foobar2000 appdata folder alongside it, but i don't know whether the track ratings and playback stats are stored there, or if they're retrievable.

**Comment by TT-ReBORN** [comment]
@silverwings15, 

no idea if it works, but I would make a theme backup of your current Georgia-ReBORN state
and make a copy of your old foobar2000 appdata folder. Then uninstall your current foobar.
Install the old foobar v1.6 version and start foobar once and close it. Then copy your old foobar2000 appdata folder
with the new one and start foobar. Go to top menu `Media` > `Playback Statistics` > `Export statistics...`
Save those xml files somewhere. Uninstall the old foobar v1.6 and install again the latest foobar.
Restore your theme backup and when successfully, try to import those statistics via top menu 
`Media` > `Playback Statistics` > `Import statistics...`. 

If that does not work, your chances do not look good... 
When I updated from fb2k v1.6 to v2.0, playlists and statistics were automatically converted to the new foobar format.
From now on, you should use the theme backup feature and everything will be good...

Btw, I always recommend to use portable foobar installation as it is much better and also easier to use 
with much more freedom...

-Tom

**Comment by PSVLTT** [comment]
@TT-ReBORN 
I do not know why.
But after I backup by copy paste, the backup function work fine too.

**Comment by TT-ReBORN** [comment]
@PSVLTT,

yes, you just applied the workaround I told you above.

The theme backup is working fine since RC2 version, I just extra checked.
You just had an old theme back made with the older RC1 version, that is why you had the missing configuration dir 
and popup notice.

There should be no issues when making theme backups with RC2 or newer versions ( DEV ) and you won't get any errors.

-Tom

**Comment by PSVLTT** [comment]
> @PSVLTT,
> 
> yes, you just applied the workaround I told you above.
> 
> The theme backup is working fine since RC2 version, I just extra checked. You just had an old theme backup made with the older RC1 version, that is why you had the missing configuration dir and popup notice.
> 
> There should be no issues when making theme backups with RC2 or newer versions ( DEV ) and you won't get any errors.
> 
> -Tom

Yeah, I get it. Thank you very much ^^
