### ISSUE TITLE
some tracks with 2 label logos

### ISSUE THREAD

**Issue by KenParker-CN** [TT-ReBORN/Georgia-ReBORN#183]
Some songs have two label logos, and I'm curious how this is achieved. I've noticed that within the tag, the separator for multiple labels is a semicolon (;), but when I input semicolons myself, they fail to be recognized properly. By the way, I obtain my song tags from MusicBrainz.
_I can't tell the difference between the semicolons in the original tags and those I manually input, lol._
**source label tag** OVO Sound; Warner Records  **manual** OVO Sound; Warner Records

It might be an issue related to encoding when reading the data, and Idk about it.

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/171419654/30f3831a-aa1d-4b8d-a64a-733415fbdad1)
`bottom-right label logo`

**Comment by TT-ReBORN** [comment]
Hi @KenParker-CN,

you need to `split values` when using multi-values in metadata fields.
Select the entire album ( all tracks selected ) then right click > Properties.
Right click on the `%label%` or `%publisher%` metadata field, select `Split values...` and click `OK`.
Now both values will be handled as separate values and both label logos will be displayed.

-TT

**Comment by KenParker-CN** [comment]
> Hi @KenParker-CN,
> 
> you need to `split values` when using multi-values in metadata fields. Select the entire album ( all tracks selected ) then right click > Properties. Right click on the `%label%` or `%publisher%` metadata field, select `Split values...` and click `OK`. Now both values will be handled as separate values and both label logos will be displayed.
> 
> -TT

thank u so much
