### ISSUE TITLE
Scrollbar and playlist positioning is not equal

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#19]
Apologies if this isn't a bug but instead a design choice! I noticed that there's some weird spacing going on with how the scroll bar is rendered in the playlist view, as well as where the playlist stops being rendered at the bottom.

Refer to this annotated screenshot:
![Untitled-1](https://user-images.githubusercontent.com/1534470/125325617-6d3c9b80-e341-11eb-85e3-2957e79bf063.jpg)

Distance A (at the bottom) is unexpected - is the playlist meant to be rendered all the way to the edge of the whitespace that it sits in? I would suggest extending it to the edge.
Distance B and C should be extended to the vertical start and stop of the rendering area for the playlist.

**Comment by TT-ReBORN** [comment]
I need those hidden bars ( top and bottom ) to hide the rows that shouldn't be visible when scrolling up and down.
If they are removed, there would be redraw leftovers from those scrolling rows. This is the only workaround there is to it.

The playlist arrows have the same spacing ( from playlist top to the up arrow and from playlist bottom to arrow bottom ).

You can try it out for yourself to understand it, if you remove the code from line 709 to 777 in Panel_Playlist.js 
and play around with the scrolling it will happen...
