### ISSUE TITLE
Album art cover quality regression

### ISSUE THREAD

**Issue by emotion3459** [TT-ReBORN/Georgia-ReBORN#192]
Caused by https://github.com/TT-ReBORN/Georgia-ReBORN/commit/561198494e8cd8672d6401660ce3b7d2d3a42ddb
[Comparison](https://slow.pics/c/PDhEzgCP)

Passing InterpolationMode.HighQualityBicubic to DrawImage doesn't make any difference to the interpolation quality, this seems to be a no-op.
The original code was blurrier *because* of the higher quality scaling. "High Quality" implies expanding the kernel radius by the downscale factor in order to prevent aliasing (and as a side effect makes the image a little softer).
The new code is sharper, yes, but now there is aliasing as a result. It is considered "wrong" to scale images this way.

As a side note, I saw this comment:
> Avoid weird anti-aliased scaling along border of images

These artifacts are caused by the kernel sampling outside of the image boundaries, it seems GDI zero pads the samples by default instead of mirror padding. Supposedly PixelOffsetModeHighQuality fixes this.

**Comment by TT-ReBORN** [comment]
> Passing InterpolationMode.HighQualityBicubic to DrawImage doesn't make any difference to the interpolation quality, this seems to be a no-op.

Whoops you're right, just checked the Spider Monkey Panel docs...
That was a fail, I'll revert this change because InterpolationMode.HighQualityBicubic doesn't apply it at all 😅 
The ~35% performance boost and sharpness of the new method blinded me.

The old method is really the only workaround because unfortunately you can not use `PixelOffsetModeHighQuality`. 
There is no such method available or implemented SMP.

GDI still sucks and I hope that we can get Direct2D rendering in the future...

-TT

**Comment by TT-ReBORN** [comment]
> These artifacts are caused by the kernel sampling outside of the image boundaries, it seems GDI zero pads the samples by default instead of mirror padding. Supposedly PixelOffsetModeHighQuality fixes this.

[Here is the topic of the issue that was also in the comment you pointed out](https://stackoverflow.com/questions/4772273/interpolationmode-highqualitybicubic-introducing-artefacts-on-edge-of-resized-im).

**Comment by silverwings15** [comment]
has this actually been fixed? i'm using the latest Master with the playlist background image feature implemented and the quality of album art has degraded significantly

**Comment by silverwings15** [comment]
ok, so it happens only when you don't specify the artwork directories in foobar preferences and foobar grabs whatever image is available in the album directory (i made sure that there was no low res artwork file in the album directory)

**Comment by TT-ReBORN** [comment]
Yes, it is using the old original method, I reverted the commit.

It's possible you were using another fetching method in foobar's `Preferences` > `Advanced`:
Filter: `embedded` -> `Display` > `Album art` > `Embedded vs external`. I have it on `Prefer larger`.

-TT
