### ISSUE TITLE
Sometimes artwork does not display on Details tab

### ISSUE THREAD

**Issue by PSVLTT** [TT-ReBORN/Georgia-ReBORN#194]
Hi TT,
I wonder this is bug or not,
Some of albums from my collection does not auto cycle display artworks on "Details" tab. - Yes, some specific albums, not random.
And the option "Display next artwork" not appear on context menu too.
Even though I have images on the folder of Album.

And I want to ask more: How to change time auto cycle artwork (default 30s)?

Thank you~!

![image](https://github.com/user-attachments/assets/509a8af9-cccf-4742-91f9-41d87432d069)
![image](https://github.com/user-attachments/assets/9c68c98a-bb41-4639-8715-85b6d82be502)

**Comment by TT-ReBORN** [comment]
Hi @PSVLTT,

try the latest update from here: https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/74#discussioncomment-11206556 .

It also has the option to change the cycle time for the main album art in:
`Top menu` > `Options` > `Player controls` > `Album art` > `Cycle album artwork` > `Cycle time`.

-TT

**Comment by PSVLTT** [comment]
Hi @TT-ReBORN 
I tested it, the problems still appears.
Beside, I feel more slow/laggy when I use this version. 
Maybe I need time to test more.
Thank you, sir!

**Comment by PSVLTT** [comment]
Hi @TT-ReBORN 
I found the reason.
If the "Album Artist" feild has more than 1 Album Artist. 
The problem will appear.
Can you fix it?

**Comment by TT-ReBORN** [comment]
Hi @PSVLTT,

I see the issue now, you are using the semicolon `;` in the folder name in your screenshot.
`Various Artists;` 

This can not be fixed because it is a Spider Monkey Panel issue, I have already reported it here:
https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/234

So do not use semicolons `;` in your folder names but use a different one. e.g `-` or `&`

-TT

**Comment by PSVLTT** [comment]
> Hi @PSVLTT,
> 
> I see the issue now, you are using the semicolon `;` in the folder name in your screenshot. `Various Artists;`
> 
> This can not be fixed because it is a Spider Monkey Panel issue, I have already reported it here: [TheQwertiest/foo_spider_monkey_panel#234](https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/234)
> 
> So do not use semicolons `;` in your folder names but use a different one. e.g `-` or `&`
> 
> -TT

Thank you! I will try another way!

**Comment by TT-ReBORN** [comment]
@PSVLTT,

actually I have applied a functional workaround which does now also support semicolons `;` in directory names.
It is now implemented in the master here:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

-TT

**Comment by PSVLTT** [comment]
Hi @TT-ReBORN 
Thank you very much.
But I can't really use this version, because performance problems:
- The "Biography" Tab laggy, slow respond when click
- Click switch between tabs laggy, slow respond
- Almost all actions on playlist laggy, very slow (scroll, click, search...)

- My PC specs: AMD Ryzen 3 3300X, 16GB RAM, all tracks on SSD drive (not full disks)
- Test on clean install newest foobar2000_v2.24_preview_2024-11-14 and clean, only the theme from file "master.zip"
- All works fine on version: I do not remember exactly the version, my lastest update about April 2024.

**Comment by TT-ReBORN** [comment]
@PSVLTT,

the latest version has worse performance for you? How come?
Actually it should be better performance than from April!

Is it possible if you could tell me from which date it has gotten worse performance for you?
You can browse here: https://github.com/TT-ReBORN/Georgia-ReBORN/commits/master/
Then you see the commits and its dates, you can go to the bottom for next page till you reach the date range
you think it is good and choose a date ( click on the `<>` button ). This will choose the archive snapshot of the version.
You will be redirected to the main page, at the top of the website, click on the green (or sometimes blue ) Code <> button and click `Download zip`.

You can then make a test portable foobar installation and install the archive version you downloaded.
If you could tell me from which date is has worse performance, I could take a look what happened.

-TT

**Comment by TT-ReBORN** [comment]
I have restored an original method ( the same as it was in April ) that is more efficient 
and should have smoother experience. You can try the latest version from master:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

Also the latest version has better performance than the version from April, I have tested both side by side for several hours.
The biography script downloads all images and processes them when they are not already downloaded and in cache. 
It is not the issue of the script, but because your slow CPU has poor single-thread performance.

-TT

**Comment by PSVLTT** [comment]
> I have restored an original method ( the same as it was in April ) that is more efficient and should have smoother experience. You can try the latest version from master: https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip
> 
> Also the latest version has better performance than the version from April, I have tested both side by side for several hours. The biography script downloads all images and processes them when they are not already downloaded and in cache. It is not the issue of the script, but because your slow CPU has poor single-thread performance.
> 
> -TT

Thank you sir, maybe I will upgrade my cpu :D
