### ISSUE TITLE
White window on fresh install on Ubuntu

### ISSUE THREAD

**Issue by MvCast** [TT-ReBORN/Georgia-ReBORN#195]
Hi there,

I have been trying to install it following the Installation Guide, but I always get white window.

I have used the 32-bit installer from the official web site, installed it as a portable installation, copied the profile folder to the root directory and installed the fonts.

I don't know what I could be doing wrong. When I make a clean install of foobar on its own it works fine. Maybe I am missing a package or something like that? 

I am kind of lost. Would appreciate any help. Whatever needed, I would provide.

Many thanks in advanced.

**Comment by TT-ReBORN** [comment]
Hi @MvCast,

I think you misunderstood the installation instructions.
When you do a standard foobar installation, you need to copy the **content of the profile** directory from the zip:
- configuration
- eslyric-data
- georgia-reborn
- user-components

For the portable installation you **copy the entire profile** directory from the zip.

Also here is a simple Linux guide how to install it:
https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/1#discussioncomment-9011982

-TT
