### ISSUE TITLE
Switching back from 4K mode does not reset library font size

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#24]
To reproduce:

1. Start the player in the "Small" size
2. Change the player to "Large" size
3. Set "Use 4K mode" to "Always"
4. Set "Use 4K mode" to "Auto-detect"
5. Change player back to "Small" size

The result is this:
![image](https://user-images.githubusercontent.com/1534470/125570002-c1361bd5-30bb-4602-b9b8-59ebe1c496d3.png)

Using Library settings > Reset library zoom doesn't appear to change the font size other than by a size or two. I need to then use Change font sizes > Library > Default.

**Comment by TT-ReBORN** [comment]
Can't reproduce, you told me you're using a QHD res monitor.
Is it 2560x1600 or 2560x1440 ? This is important to know.

**Comment by takaji10** [comment]
My monitor is 2560x1440, Dell U2715H.

Trying the first scenario, the library font size did not reset.
Trying the second scenario, where I started with 4K set to "never," changed to "always," and then back to "never" - in this case the font size changed back to the 16px default value.

**Comment by TT-ReBORN** [comment]
Hey @takaji10,

try the latest commit and tell me if this fixed the issue. 

Thanks!

**Comment by takaji10** [comment]
I tried switching from use 4K always, and then back to auto-detect, and the font size in the library view is now correct again. Thanks for fixing this bug! :)
