### ISSUE TITLE
16 px font size on lower bar looks bad

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#29]
Default size (18 px):

![image](https://user-images.githubusercontent.com/1534470/127283270-943f3bd6-f8b4-4881-8fdd-685e361c26d9.png)

16 px size:

![image](https://user-images.githubusercontent.com/1534470/127283342-6eb535ff-f356-4541-ad0b-e3f132eadd7d.png)

Resizing to 20 px and up produces no problems.

Should the button size also be changing when switching font size? I thought this was controlled separately by Player controls > Transport button size/spacing?

**Comment by TT-ReBORN** [comment]
Thanks @takaji10,

fixed it, added also additional independent lower bar font scaling in compact mode.

-TT

**Comment by TT-ReBORN** [comment]
God damn copy and paste errors, needed to push the same commit 3 times... =)
