### ISSUE TITLE
Show composer in lower bar shows hyphen when %composer% is not present

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#30]
![image](https://user-images.githubusercontent.com/1534470/127493919-a72c035a-dc7f-45fa-a3be-8525a6fd3d57.png)

Looks like the " - " part needs to be moved inside the [].

**Comment by TT-ReBORN** [comment]
I don't have this, all is good on my side.
 
Can you try and replace line 23 with this: 
tf.composer = '[ - %composer%]';  

instead of the old one, in defaults.js ?

**Comment by takaji10** [comment]
Argh, I found out what it is - when you rip a CD in EAC, it always adds empty %composer% tags to the files. I usually spot this in my old layout, but in this new one you don't see composers until the song is playing in the playbar below. So it's not a bug, it's just me. :P
