### ISSUE TITLE
Playlist Manager

### ISSUE THREAD

**Issue by onceagain911** [TT-ReBORN/Georgia-ReBORN#36]
Why not remake the playlist manager? I think the function of the current playlist manager is too simple, if you can be modified like Br3tt's JS Smooth Playlist Manager. It will be more convenient to use! This is just a suggestion! tks!

**Comment by TT-ReBORN** [comment]
Hi,

can you tell me what's the difference between the playlist manager in this theme and Br3tt's JS Smooth Playlist Manager?
All I can remember is the auto-playlist/presets...

-TT

**Comment by onceagain911** [comment]
basic list management functions, rename lists, sort lists and  auto-playlist/presets

**Comment by TT-ReBORN** [comment]
You can all do that in the playlist manager, if you click on it or just hit CTRL+M. 
Maybe in the future I'll add the auto-playlist feature, for now I need to do other important things...

-TT

**Comment by TT-ReBORN** [comment]
I have added the ability to create your own custom auto playlists and some presets.
It is available in the latest commit, download and overwrite your existing files.

You can find and access the auto playlist feature in three different ways:
1. In the top of the playlist ( mouse hover ) header, then click on the font > Create new auto playlist
2. Right click for context menu in the playlist > Create new auto playlist.
3. In the top menu "Playlists" > Create new auto playlist

Now the playlist manager has the same functionality as Br3tt's JS Smooth Playlist Manager.

-TT
