### ISSUE TITLE
Opening a file not refreshing playlist

### ISSUE THREAD

**Issue by tygrysmalajski** [TT-ReBORN/Georgia-ReBORN#37]
After opening a new file the playlist stays unchanged. Reproduces on abfe27f.

**Comment by TT-ReBORN** [comment]
Hi @tygrysmalajski,

can you elaborate on this? What do you mean "After opening a new file" ?
Drag and drop to playlist works, and File > Add files/folder also works and updates the playlist.
On my end everything is good.

Did you try on a new clean portable installation? Lots of files and config files have changed.

Thank you!

-TT

**Comment by tygrysmalajski** [comment]
Clean installation resolved the issue.

Thanks
