### ISSUE TITLE
Couple of minor bugs

### ISSUE THREAD

**Issue by silverwings15** [TT-ReBORN/Georgia-ReBORN#42]
hey TT, now that i've switched to Georgia-ReBORN for good, i hope you won't mind me reporting the occasional bugs i come across 😁

1. When you start playing new items from the Library view, and then switch to Playlist view (by clicking either Library again or Biography), the playlist is correctly updated with the new tracks. however, if you click Lyrics panel, then the old playlist still remains instead.

2. When changing the scroll speed in Panel settings (the defaults seem to be reaally slow, perhaps you can consider updating them, i'm currently using 10 step and 200 ms duration), the new settings are applied to Library view but NOT Playlist view.

and if it needed to be said.. you took what is already an amazing theme by Mordred and made it even better than anyone can imagine, so you both have my utmost appreciation for that. now i can finally retire my DarkOne themes which i've used for a total of about 10 years at this point.. RIP Tedgo

**Comment by TT-ReBORN** [comment]
Hi @mimecry, 

thanks for the bug report and glad you like the theme! 
I'll look into these when I have the chance, first I need to finish other things related to Georgia-ReBORN.

-TT

**Comment by TT-ReBORN** [comment]
Ok, the playlist refresh from adding items from Library and switching to Lyrics has been fixed.

Actually the mouse wheel scroll step panel settings is not a bug. The panel setting you have changed applied only to the Library and not for Playlist and Biography. So I have implemented mouse wheel scroll options to change behavior for Playlist, Library and Biography.

You can find these new settings in top menu Options > Player controls > Scrollbar settings

Download the latest version from [here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip) and replace your existing files.

Thanks for the report!

-TT

**Comment by silverwings15** [comment]
fixes are working as intended, thank you!
