### ISSUE TITLE
Problem with cover

### ISSUE THREAD

**Issue by BEST8OY** [TT-ReBORN/Georgia-ReBORN#62]
Hello
I have an issue with showing cover in details section.
When next to my songs files there is a picture, foobar shows that picture in details section instead of showing front cover?
How can I fix it?

**Comment by TT-ReBORN** [comment]
Hi,

can you please describe your problem? This information you've provided is not helpful at all.
First check if you album cover is cover.jpg/png or folder.jpg/png and you have it in your album folder.
Second, check if you have embedded images in your music files.

-TT

**Comment by BEST8OY** [comment]
> Hi,
> 
> can you please describe your problem? This information you've provided is not helpful at all. First check if you album cover is cover.jpg/png or folder.jpg/png and you have it in your album folder. Second, check if you have embedded images in your music files.
> 
> -TT

Sorry for not providing enough info.
Examples:
https://imgur.com/a/vIsoYXA
If more than one picture be in Folder , Foobar randomally choose one of pictures to show. I mean if both photo of exmaples be in folder foobar choose picture with numbered file name

**Comment by TT-ReBORN** [comment]
**Album cover must always be named cover.jpg/png or folder.jpg/png in your album folder, then it will show the album cover correctly.** This is the standard for all music players. If these files with the names are not present, it will cycle through your embedded images in your music files ( flac/mp3).

For more information how the folder structure should look like see in FAQ: "How do you display the disc art in Details?"
https://github.com/TT-ReBORN/Georgia-ReBORN#faq

-TT

**Comment by BEST8OY** [comment]
> **Album cover must always be named cover.jpg/png or folder.jpg/png in your album folder, then it will show the album cover correctly.** This is the standard for all music players. If these files with the names are not present, it will cycle through your embedded images in your music files ( flac/mp3).
> 
> For more information how the folder structure should look like see in FAQ: "How do you display the disc art in Details?" https://github.com/TT-ReBORN/Georgia-ReBORN#faq
> 
> -TT

Well as you saw my example there is no cover or folder but foobar shows a picture in the folder with whatever name.
The two music of my examples have an embedded image as front cover.
My question is:
Why foobar shows those picture which don't have cover.jpg/png name?

**Comment by TT-ReBORN** [comment]
Yes, it's not about disc art but in the FAQ it will show you the folder structure and how the images in the album folder should look like. OK, so in your case it will show any *.jpg/.png images that are present in the album folder and last it will check and try embedded images in music files. 

You can open your georgia-reborn-config.jsonc file ( located in foobar2000\profile\georgia-reborn ) and go to section:
`"imgPaths": [`

remove the lines that have *jpg or *png, for example:
`"$replace(%path%,%filename_ext%,)*.jpg",`
`"$replace(%path%,%filename_ext%,)*.png",`

Save your georgia-reborn-config.jsonc and restart foobar.

With this it will not show any random jpg or png images that are in your album folder...
Anyways, you should always have at least one album cover in your album folder.

-TT

**Comment by BEST8OY** [comment]
Thanks a lot
I added two // for those lines and made those lines inactive
This way
```
// "$replace(%path%,%filename_ext%,)*.jpg",
// "$replace(%path%,%filename_ext%,)*.png",
```
I know I should have a cover for album in it's folder unless album music files already have an embedded cover.
My issue was for not moving single music from my download folder which I also download my pictures to there.
It all is about my laziness for not moving my music to an appropriate location. :)
