### ISSUE TITLE
does it support hdpi? font size looks so much different when i move between screens

### ISSUE THREAD

**Issue by CuiYongen** [TT-ReBORN/Georgia-ReBORN#63]
my laptop is 14-inch with a 27-inch monitor
it looks so fine when both in all-screen mode，but not when moving between screens
is there anyway to solve it (maybe by settings that i haven't noticed?)
![1](https://user-images.githubusercontent.com/12591929/163706461-cd0cfc66-1797-4d8c-8985-fdc486f2cece.gif)

**Comment by TT-ReBORN** [comment]
Try the latest update, just released now!

If you installed it, you can manually switch to different display resolutions in top menu Options > Display.

-TT
