### ISSUE TITLE
tray icon disappeared

### ISSUE THREAD

**Issue by CuiYongen** [TT-ReBORN/Georgia-ReBORN#64]
after installed theme, tray icon desappeared
<img width="371" alt="image" src="https://user-images.githubusercontent.com/12591929/163707065-fe7635a1-e140-4036-ae73-e2bba4d3fccf.png">

**Comment by TT-ReBORN** [comment]
Hi @CuiYongen,

you need to select, Columns UI ( **not Default User Interface** ) > Notifications area tab > Always show icon/Use custom icon.

-TT
