### ISSUE TITLE
GdiPlus error: DrawImage failed with error (0x7): Win32Error

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#66]
I was dragging and dropping a folder of music into a playlist and encountered this crash.

Error: Spider Monkey Panel v1.6.2-dev+7c0928bf ({04620F16-1878-47A1-8EFE-0CE0B99566CC}: Georgia-ReBORN v2.0.3b by TT)
Resize failed:
GdiPlus error: DrawImage failed with error (0x7): Win32Error

File: main.js
Line: 4517, Column: 21
Stack trace:
  assign_art@main.js:4517:21
  getHeaderArtwork/</<@main.js:3017:12

**Comment by takaji10** [comment]
Ouch, I can't recover from this crash. Tried reloading the configuration and it continues to crash.

**Comment by TT-ReBORN** [comment]
Damn... 

did you use any theme styles? 

When the crash screen occurs, try right click > Panel Properties > Clear.

**Comment by takaji10** [comment]
I see what the issue is - the cover.png in the folder was corrupted. You might want to include some way to recover from this?

**Comment by TT-ReBORN** [comment]
By any chance are you using, in File > Preferences > Display > In the album art / Front cover:

folder.jpg
folder.png
cover.jpg
cover.png
front.jpg
front.png
%filename%.jpg
%album%.jpg

these?

**Comment by takaji10** [comment]
I've got this:

cover.jpg
cover.png
cover.jpeg
..\cover.jpg
..\cover.jpeg
..\cover.png
