### ISSUE TITLE
this.playing_item is undefined

### ISSUE THREAD

**Issue by takaji10** [TT-ReBORN/Georgia-ReBORN#70]
I encountered this error while I was looking at a different playlist while the currently playing track changed on another playlist.

Error: Spider Monkey Panel v1.6.2-dev+7c0928bf ({04620F16-1878-47A1-8EFE-0CE0B99566CC}: Georgia-ReBORN v2.0.3b by TT)
this.playing_item is undefined

File: main.js
Line: 1456, Column: 4
Stack trace:
  on_playback_new_track@main.js:1456:4
  PlaylistPanel/this.on_playback_new_track@main.js:478:12
  on_playback_new_track@georgia-reborn-main.js:3567:12

**Comment by TT-ReBORN** [comment]
Good catch! Fixed it, can you check your PM on HydrogenAudio?
I'll release several fixes, want to include the other fix too...
