### ISSUE TITLE
Lyrics are not shown for a reason I can't figure out

### ISSUE THREAD

**Issue by pityalvarez** [TT-ReBORN/Georgia-ReBORN#73]
There is:
Multi source lyrics
OpenLyrics (there's a big update on this so I installed it but It didn't change, It would be good if in the Master it was checked that all It's up to date)
Lyric Show Panel
I can't trace which one causes this.
Maybe It's the Id3 tag of the song, but I try but it isn't

**Comment by TT-ReBORN** [comment]
Hi @pityalvarez,

Georgia-ReBORN uses the user-component Lyric Show Panel 3 ( foo_uie_lyrics3 ) and Multi-source lyrics ( foo_multisource ).
The theme does not use or support foo_openlyrics, I would like to replace these two components ( foo_uie_lyrics3 and foo_multisource ) with foo_openlyrics, but currently it does not support lyrics for radio streaming which other users are using...

To fix your issue there are couple of things you can try:
1. Backup your foobar folder.
2. Remove the OpenLyrics component, it is possible that it bugs out the Lyric Show Panel 3 component.
3. I don't know if you changed options in the preferences, regardless of that download the master.zip from [here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip) open the zip and go to profile\configuration\
extract foo_multisource.dll.cfg and foo_uie_lyrics3.dll.cfg and replace your existing files.
4. Restart foobar and see if it works. 
5. If not, you need to make a new portable installation.

-TT
