### ISSUE TITLE
Gap problem on windows

### ISSUE THREAD

**Issue by ArthAttack** [TT-ReBORN/Georgia-ReBORN#76]
I've been trying to use this theme for the past 1 year or so, and everytime i try this gap between the album art and the left side of the screen always trows me back to another theme, the Option -> Player controls -> Album art settings -> When player size is not proportional option doesn't seens to do anything

![foobar2000_YSyFR42cfc](https://user-images.githubusercontent.com/86346283/194053903-c26d6bcf-8639-4706-93b4-1d190d4a31d2.png)

![image](https://user-images.githubusercontent.com/86346283/194054062-4fec1b45-8e15-4c02-ab2b-95c377ee435a.png)

**Comment by TT-ReBORN** [comment]
I don't know which version you're using, but there are no issues in the latest beta version.
When the player size is not proportional, there will be a gap as you've shown in the screenshots.
With top menu Options > Player controls > Album art > When player size is not proportional
you can use various options how the album art will be aligned. 
And no, it should not change to a different theme when you use this option.

Also if the player has the right size ( Options > Player size ), there will be no gap at all.

Try making a new portable installation and get the latest Beta version from the thread [here](https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/74).

The version on the main Github page is half a year old and will be updated once the beta testing is finished, which will be soon.

-TT
