### ISSUE TITLE
Exif data on images and other optimizations

### ISSUE THREAD

**Issue by regorxxx** [TT-ReBORN/Georgia-ReBORN#88]
Have found multiple images at 'georgia-reborn\images\' with unnecessary exif data.
Also some of them could be losslessly compressed using Caesium. (the difference is almost none though)

Attached all the image files processed:
[images.zip](https://github.com/TT-ReBORN/Georgia-ReBORN/files/9913835/images.zip)

All image files processed, but disc art not compressed:
[images.zip](https://github.com/TT-ReBORN/Georgia-ReBORN/files/9913978/images.zip)

Record Labels:
https://tmpfiles.org/dl/199416/recordlabel.zip

Artist Logos:

**Comment by TT-ReBORN** [comment]
I've already used PNGOO for compression, but you can not use any compression at all on the disc art placeholders.
I've tried multiple compressors and they have all problems with round transparency ( alpha mask ). In 4K and even in FHD it's visible when the disc art is spinning. There will be artifacts ( with flickering and cut edges ) on the edges of the disc, so we can't use any compression at all on those...

**Comment by TT-ReBORN** [comment]
The exif data can be of course removed...

**Comment by regorxxx** [comment]
I may be wrong, though, but don't see any effect on the disc arts I compressed on 4K.

Anyway let me redone it, to compress the rest and EXIF for all then. Omitting compression for the disc art.

**Comment by TT-ReBORN** [comment]
It's only visible when the disc art is spinning, when it is not rotating it's not visible. 
I've tried 6 different compressors and all failed. It's also more visible on different disc art placeholders than others, with different background colors. Until I've figured this out, it took me a day, I thought there was some GDI+ bug ;)

**Comment by regorxxx** [comment]
My screenshot is while spinning though; just in case you want to take a look at it by yourself; unless I'm missing what to look for, it works fine on my side.

See at top for files.

**Comment by TT-ReBORN** [comment]
Ok I'll check on my 4K monitor.

**Comment by TT-ReBORN** [comment]
Seems good replaced it already with my main files, thanks! Well I've used a little more aggressive compressors which are great but only if you using it as a still image. They have saved 70% space but can't use them on the disc arts :(

Hey you can't imagine what GDI+ bugs will happen when you're working on my theme, it's really getting on my nerves to use workarounds, example gr.gradRect... ;)

**Comment by regorxxx** [comment]
Artist and record logos will be ready on a few minutes too. They are uploaded to a temp server though.

**Comment by TT-ReBORN** [comment]
Don't do them, they are linked to Mordred's repo as he manages them and people are using the link from the readme.
He updates them monthly or so as he also is a moderator on fanart.tv

**Comment by regorxxx** [comment]
> Seems good replaced it already with my main files, thanks! Well I've used a little more aggressive compressors which are great but only if you using it as a still image. They have saved 70% space but can't use them on the disc arts :(
> 
> Hey you can't imagine what GDI+ bugs will happen when you're working on my theme, it's really getting on my nerves to use workarounds, example gr.gradRect... can not use 90° most of the time on large width ;)

Did that happened with lossless compression? Because that smells like a bug... they output files should be fully functional. Other thing is using lossy compression though. And yep, I don't understand many things with GDI XD, most times I just put values there until something works. Specially for arc values, degrees, etc. 

In fact have been fighting with that today on updating my buttons UI, since I thought the buttons at top on Georgia looked great with no background. And managed to mimic the animation and shades from native foobar pretty great I think.
![theme3](https://user-images.githubusercontent.com/83307074/199346535-e872f88b-1e8f-4c26-83a3-93ff0d6cd2c0.gif)

**Comment by regorxxx** [comment]
> Don't do them, they are linked to Mordred's repo as he manages them and people are using the link from the readme. He updates ( adding new ones ) them monthly or so as he is also is a moderator on fanart.tv

Ok! Was not sure if he was gonna update them anymore.

**Comment by regorxxx** [comment]
Closing this since there are no more changes needed-

**Comment by TT-ReBORN** [comment]
Yep, lossy png compression, not a GDI+ bug :)

**Comment by TT-ReBORN** [comment]
Yeah, for arc values I need to put a try catch over it, i.e theme style round progress bar, otherwise it would crash since arc value is undefined at the start of playing a song... but yea they lots of tricks and workaround when using the graphics ;)
