### ISSUE TITLE
Option to display lyrics while moving to other menus

### ISSUE THREAD

**Issue by RafeeDaBoy** [TT-ReBORN/Georgia-ReBORN#89]
In the origin Georgia theme, you could keep the lyrics visible whilst going through the other menus. 

https://user-images.githubusercontent.com/69535896/199346620-82d4b1ed-bc4d-43d2-830b-5103331a8212.mp4

So it'd be nice to make the lyrics a toggle instead of a separate menu

**Comment by TT-ReBORN** [comment]
Hi @RafeeDaBoy,

I could make an option for that, but lyrics top menu button will always stay there.
Since Beta 10, you can hide the top menu buttons via Options > Player controls > Top menu.

-TT

**Comment by RafeeDaBoy** [comment]
That'd be awesome! I don't mind the button, just making the lyrics persistent across the other menus would be nice. Thanks a lot for your time!

**Comment by TT-ReBORN** [comment]
Now available in Beta 10c: https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/74#discussioncomment-4140202

**Comment by RafeeDaBoy** [comment]
Awesome, thanks a lot!
