### ISSUE TITLE
Clickable Rating column

### ISSUE THREAD

**Issue by vfxturjo** [TT-ReBORN/Georgia-ReBORN#92]
Hi, the theme is awesome!!!

I regularly rate my songs. 
I used to use iTunes years back, then I started using foobar2000, and was using SimPlaylist. both iTunes and f2k SimPlaylist allowed me to rate my files.

![image](https://user-images.githubusercontent.com/44445014/201057308-9cde24bc-99c6-4d54-ab8a-055a6ce9a97b.png)
1. I click on the Rating column to set rating
2. I have autoplaylists which are for certain rated songs...

When I rate a song, it uses Metadata in the file for storing the rating value. So, whereever I go, I get my ratings.
![image](https://user-images.githubusercontent.com/44445014/201055518-8d195dce-1834-4c68-81b4-30320a42856b.png)
this <RATING> tag...

Now, i want to
1. use that metadata to display ratings in the column of Georgia-ReBORN
2. click directly on the column to set Rating of a song, which will write in the same <RATING> column

How to do it??
Thanks in advance!!

**Comment by TT-ReBORN** [comment]
Now available in Beta 10c: https://github.com/TT-ReBORN/Georgia-ReBORN/discussions/74#discussioncomment-4140202
